### ISSUE TITLE
Install Network Attack specific dependencies

### ISSUE THREAD

**Issue by higgyCodes** [gremlin/gremlin-playground#3]
Network attacks do not have the required packages to install.

This is due to our specific operating system, CentOS Linux 8  - RHEL Fedora

John has suggested that the required package is most probably `iproute-tc`

**Comment by higgyCodes** [comment]
I was able to add iproute-tc and get a different error message:

`Error: Specified qdisc not found.`

Reading through documentation it looks like I should add the `kernal-modules-extra` package
`kernel-modules-extra`

But  I'm still getting the same error messaging after that install

**Comment by jyee** [comment]
Installing `kernel-modules-extra` and `iproute-tc` definitely resolved the issue. I'm going to see if there's a way we can be more specific about what to install, since `kernel-modules-extra` also installs `kernel-modules` and `kernel-core` which adds a lot of weight.

**Comment by jyee** [comment]
I just added https://github.com/gremlin/gremlin-playground/tree/jyee/fix_network_attacks

When adding `kernel-modules-extra` it also upgrades the kernel from `4.18.0-193` to `4.18.0-240`. I think that's part of the strangeness: it depended on which kernel was booted after the image was built. The branch linked above removes `193` after the upgrade.

However, the zipped VM is now ~100MB larger, so we'll want to strip out a lot of the unnecessary drivers and other modules.

**Comment by jyee** [comment]
🤦  I forgot that I could just add that via the kickstart file and it adds almost nothing to the compressed vm. Gonna do a bit of testing and then roll an updated release tomorrow.
